version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    image: premnikumbh/simple-java-maven-app:latest
    container_name: simple-java-maven-app
